# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XLLxGa9ZCgSIP25cIGn66aqOvCTVcg-l
"""

!pip install gradio
!pip install langchain-google-genai
!pip install langchain-anthropic
!pip install -U langchain-core langchain-mistralai
!pip install langchain-groq
!pip install langchain-cohere

from google.colab import drive
drive.mount('/content/drive')
!cd /content/drive/MyDrive/LLM_Arena

import sys
sys.path.append('/content/drive/MyDrive/LLM_Arena/')

import importlib
import llms
importlib.reload(llms)

import gradio as gr
from llms import model_functions

def compare_selected_models(prompt, model1_name, model2_name):
    model1_response = model_functions[model1_name](prompt)
    model2_response = model_functions[model2_name](prompt)
    return model1_response, model2_response

model_names = list(model_functions.keys())

interface = gr.Interface(
    fn=compare_selected_models,
    inputs=[
        gr.Textbox(lines=2, placeholder="Enter your prompt here..."),
        gr.Dropdown(choices=model_names, label="Select First Model"),
        gr.Dropdown(choices=model_names, label="Select Second Model")
    ],
    outputs=[
        gr.Textbox(label="Model 1 Response"),
        gr.Textbox(label="Model 2 Response")
    ],
    title="LLM Arena",
    description="Select two models from the dropdown menus to compare their responses."
)

interface.launch()