# -*- coding: utf-8 -*-
"""LLMs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XY_PjrtsAzpy86deCCklSQBN9avLZY-s
"""

from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_anthropic import ChatAnthropic
from langchain_mistralai.chat_models import ChatMistralAI
from langchain_groq import ChatGroq

# Google AI's Gemini model

gemini_model = ChatGoogleGenerativeAI(model="gemini-pro", google_api_key=GOOGLE-API-KEY)
def gemini_response(prompt):
  response = gemini_model.invoke(prompt)
  return response

# Anthropic model

claude_model = ChatAnthropic(model='claude-3-opus-20240229', api_key=ANTHROPIC-API-KEY, temperature=0)
def claude_response(prompt):
   response = claude_model.invoke(prompt)
   return response.content

# MistralAI model

mistral_ai_model = ChatMistralAI(api_key=MISTRALAI-KEY)
def mistral_ai_response(prompt):
  response = mistral_ai_model.invoke(prompt)
  return response

# Groq LLaMA3 8b model

llama3_8b_model = ChatGroq(temperature=0, groq_api_key=GROQ-API-KEY, model_name="llama3-8b-8192")
def llama3_8b_response(prompt):
  response = llama3_8b_model.invoke(prompt)
  return response

# Groq Mixtral 8x7b model

mixtral_8x7b_model = ChatGroq(temperature=0, groq_api_key=GROQ-API-KEY, model_name="mixtral-8x7b-32768")
def mixtral_8x7b_response(prompt):
  response = mixtral_8x7b_model.invoke(prompt)
  return response

# Groq LLaMa3 70b model

llama3_70b_model = ChatGroq(temperature=0, groq_api_key=GROQ-API-KEY, model_name="llama3-70b-8192")
def llama3_70b_response(prompt):
  response = llama3_70b_model.invoke(prompt)
  return response

# Groq gemma 7b model

gemma_7b_model = ChatGroq(temperature=0, groq_api_key=GROQ-API-KEY, model_name="gemma-7b-it")
def gemma_7b_response(prompt):
  response = gemma_7b_model.invoke(prompt)
  print(response.content)

model_functions = {
    "Google AI's Gemini": gemini_response,
    "Anthropic's Claude": claude_response,
    "MistralAI": mistral_ai_response,
    "Groq LLaMA3 8b": llama3_8b_response,
    "Groq Mixtral 8x7b": mixtral_8x7b_response,
    "Groq LLaMa3 70b": llama3_70b_response,
    "Groq Gemma 7b": gemma_7b_response,
}
